# Based on celebA
data:
  type: cifar10
  train_dir: data/ #cifar-10-batches-py
  test_dir: data/ #cifar-10-batches-py
  lsun_categories_train: bedroom_train
  lsun_categories_test: bedroom_test
  img_size: 32
  nlabels: 1
generator:
  name: resnet
  kwargs:
    nfilter: 32
    nfilter_max: 256
    embed_size: 1
discriminator:
  name: resnet
  kwargs:
    nfilter: 32
    nfilter_max: 256
    embed_size: 1
    vgan_latent_dim: 256
z_dist:
  type: gauss
  dim: 256
training:
  out_dir: output/cifar10_gradpenal
  gan_type: standard
  reg_type: real
  reg_param: 10.
  batch_size: 64
  nworkers: 0 #32  
  take_model_average: true
  model_average_beta: 0.999
  model_average_reinit: false
  monitoring: tensorboard
  sample_every: 10000
  sample_nlabels: 20
  inception_every: 15620
  compute_fid: true
  fid_sample_size: 10000
  save_every: 18000  
  backup_every: 40000 
  stop_epoch: 1000
  restart_every: -1
  optimizer: rmsprop
  lr_g: 0.0001
  lr_d: 0.0001
  lr_anneal: 1.
  lr_anneal_every: 150000
  d_steps: 1
  equalize_lr: false
  adaptive_beta: false
  kwargs:
    beta_step: 0.00001
    target_kl: 0.1
test:
  batch_size: 16
  sample_size: 16
  sample_nrow: 4
  use_model_average: true
  compute_inception: false
  conditional_samples: true
interpolations:
  nzs: 10
  nsubsteps: 75
